# Generated by Django 3.0.3 on 2020-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('sallary', models.IntegerField()),
                ('is_finish', models.BooleanField()),
                ('id_client', models.IntegerField()),
                ('id_worker', models.IntegerField()),
            ],
        ),
    ]
